[package]
name = "rtr"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0.106"
serde_derive = "1.0.106"
toml = "0.5.6"
regex = "1.3.6"

[dependencies.rss]
version = "1.9.0"
features = ["from_url"]
